#!/bin/bash

# NEMO_SCRIPT_SELECTED_FILE_PATHS: newline-delimited paths for selected files (only if local)
# NEMO_SCRIPT_SELECTED_URIS: newline-delimited URIs for selected files
# NEMO_SCRIPT_CURRENT_URI: URI for current location
# NEMO_SCRIPT_WINDOW_GEOMETRY: position and size of current window

# NEMO_SCRIPT_SELECTED_FILE_PATHS: newline-delimited paths for selected files (only if local)
#for i in $NEMO_SCRIPT_SELECTED_FILE_PATHS; do
#	n=$(echo "$i"|cut -d '.' -f 1)
#	echo "$n"> "$i".toto.txt
#done



#echo $* > zob.txt

args=""
first=$(echo "$1"|cut -d '.' -f 1|tr ' ' '-')

#echo $NEMO_SCRIPT_SELECTED_FILE_PATHS|convert "$first.pdf" 2> toto2.txt 
#convert $* "$first.pdf" 2> toto.txt

while (( "$#" )); do
   clean=$(echo "$1"|cut -d '.' -f 1|tr ' ' '-')
   combox="$combox $clean"
   args="$args \"$1\""
   shift
done

name=$(zenity --entry --title="Nom du PDF" --text="Choisir ou taper le nom du PDF" $combox)
#name=$name || $first

#echo convert "$args" "$first.pdf" > ok.txt

# from http://www.imagemagick.org/Usage/files/
# You can also use '@' with the special filename '-' to read the filenames from standard input.
echo "$args" | convert @-  "$name.pdf"

#convert $args "$first.pdf" 2> toto.txt






